title: Stuff and things 
description: > # this means to ignore newlines until "baseurl:"
Projects with computers, cameras and around the house.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://rhettus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rhett Hillary # add your name
author-img: rhett.jpg # add your photo
about-author: Systems Engineer, Photographer, Traveller & Experimentor # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: Rhettus # add your Github handle
social-linkedin: rhett-hillary-30232b4 # add your Linkedin handle
#social-email: # add your Email address

# Disqus
discus-identifier: # mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
